[build]
  command = "rm -rf node_modules && npm install --legacy-peer-deps && node fix-ajv.js && CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20.11.0"
  NPM_FLAGS = "--legacy-peer-deps --force"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
