[build]
  command = "rm -rf node_modules && npm ci && CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20.11.0"
  NPM_FLAGS = "--legacy-peer-deps"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
